name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven
    - name: Build the jar
      run: mvn package
    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: GunStop-Plugin.jar
        path: target/EnergyLib-*.jar
